# Uncomment this line to define a global platform for your project
# platform :ios, ’10.0’

target 'knock4games' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'Alamofire'
 pod 'SwiftyJSON'
  # Pods for knock4games

  target 'knock4gamesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'knock4gamesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
